// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPBtfAzgcCPWVhTlynpvNZSY7pGYkujjw',
    appId: '1:822928535987:web:108de7c34dd282d3709bc6',
    messagingSenderId: '822928535987',
    projectId: 'used-market7777',
    authDomain: 'used-market7777.firebaseapp.com',
    storageBucket: 'used-market7777.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvc8khl2y8Jijz3LA6Me8nnWTz9IXViI',
    appId: '1:822928535987:android:ac2311d503510a13709bc6',
    messagingSenderId: '822928535987',
    projectId: 'used-market7777',
    storageBucket: 'used-market7777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQZ0g8Ljk2wWu3jFJbjlZLt6omHFrNXn8',
    appId: '1:822928535987:ios:f50bf79add0f83be709bc6',
    messagingSenderId: '822928535987',
    projectId: 'used-market7777',
    storageBucket: 'used-market7777.appspot.com',
    iosClientId: '822928535987-362gtkij0lrg2chm5v7n1kmb8263l519.apps.googleusercontent.com',
    iosBundleId: 'com.example.owj.usedMarket',
  );
}
